language: go
go:
- "1.12.6"
install:
- go get -d -v ./...
script:
- go test -v -cover ./...
before_deploy:
- test "$TRAVIS_PULL_REQUEST" == "false" && test -n "$TRAVIS_TAG" && make dist
- sha256sum git-lint_* > sha256sum.txt
deploy:
  provider: releases
  api_key:
    secure: KYX3F+JQjn79APIcGnQQeovBTmUil/btNFAkif9Zf1XJDGyCkVKgxqAaJi/PDOvpWj4c2h6sV20KDYmEs0i6+I6Cjf1QNitSxkVaVQGrLSsaiivWXR5fsoCgxIgwSOQ3Yjw+AOQBFJU3a0yveu0PuvdybLDX6Frs1CfruhH80wq/ObhAjbk1SbyBD7On/+yRk5uWAALu/AeOcr6tYRzhCiu3w7D1Mtf1qnFPPXDuXFwlugnx2xyz6dgHJyRRoZ0xRgqfzKs1SsJ7s9yRGZrw32uWHYIpQOKN0jwUA78ltkpJphSSde6QsSO9SwwAeEAnckWqWtXeNLRgRtF3sD2COwGIbs5xGuX6cFki8YlqRSY3LZodZ+odsMUr3QXx0O/tY+kaEcnPVhPfekuJ3vl1uLSTYOFL1ghSoLgjuvzm02qV2MfTIwajL5CD6hs7mRgC7tdwclGnAW3PEhW6K1OU4AB/qvC4fC++hQ/eK4+348hiha1nkK0zJa8GLUyGqvXJzqlvvwtkCMAjhEzWVjZ+oZ7bo6bX4UwWbLpFF996xe4D9vIyYayZxU3MscAJxEpldQAK6rOaLlOAExWaRDPXMhnEIl9wjAoRTbI5p+7cSZY+o7KISRx+MhP0lTp9lBhXFm8kV6EzznVI2uqPyvucnKhDhcFkYglNtQTTw/VUdjk=
  file:
    - git-lint_darwin_amd64
    - git-lint_linux_amd64
    - git-lint_windows_amd64.exe
    - sha256sum.txt
  skip_cleanup: true
  on:
    repo: troykinsella/git-lint
    tags: true
    go: "1.12.6"
