language: go
go:
- "1.12.6"
install:
- go get -d -v ./...
script:
- go test -v -cover ./...
before_deploy:
- test "$TRAVIS_PULL_REQUEST" == "false" && test -n "$TRAVIS_TAG" && make dist
- sha256sum git-lint_* > sha256sum.txt
deploy:
  provider: releases
  api_key:
    secure: zOcsxTEkjEZfisoydURIdS0+V/76q6KRJoPw5KYOOgZ7hoCnmf2m7YMG0tq0RqyNWk6zvGbd0q5kLgjjOeEyZWwBJJZ4UZYZB7nRCVXmcjmV+i1B8H/6EB2CQHDy6g8inyn9ig2quQQRsAJSDQILnnIvXYJzZoVcnBcxq7CcbVjRqbu+9jb8t7Bk8R/Kn5Vpy9kzG8aN6oRsnlqKKEV/TTdeKNmEhLoAHzus4twZrlOVfImePUXL16kJIQ0ZI4d4dY35thGbJlppZZNng29vUcuyDXJS2n5lkdLrnn4v9bBnZjOqI0K4qLj9t5M2Ojf2jVCA85LUowV30QW2wyZ9ehqKe6+4tZbD4gPt22A3nOdn6wpPJfWmRZ3d2W+gzaPBczROP+vkOXva8e0v3HZKnQHiCECn6Oq2YxE3J1rptaaUezUXkFMWbWo+ZISfB+7Odi1L7nIIZBW6GbxAUbeFHQytq3XYsnD7v69dqwZiqjlJ9zuNxoXb5Vzv2S7v7C5jhNT9gzDHRV150gx7cAmtE9WTA6BmF+zKeXvOBTzNJPwIKN4B5SdKlHk0gRIekjX9nhyN5s1Mh/tk+/aChlEj9wICK0szS2MbD/9VYRWTisv0m428kARZhNsD2A/buy2GXeJp8AQXyMF1baJE7MyQk85/OgjelQ31XL5dHvC8Sws=
  file:
    - git-lint_darwin_amd64
    - git-lint_linux_amd64
    - sha256sum.txt
  skip_cleanup: true
  on:
    repo: troykinsella/git-lint
    tags: true
    go: "1.12.6"
